clone_folder: c:\projects\myproject
shallow_clone: true

image:
  - Visual Studio 2015
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: "8"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install typescript
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build:ts
  = npm run jslint

on_success:
  - npm run cov:coveralls

build: off
deploy: off
skip_tags: true

